export type RootStackParamList = {
  Splash: undefined;
  Home: undefined;
  QuranArabic: undefined;
  QuranPart1: undefined;
  QuranPart2: undefined;
  QuranPart3: undefined;
  QuranPart4: undefined;
  Part1Lessons: undefined;
  Part3Lessons: undefined;
  'lesson-1': undefined;
  'lesson-2': undefined;
  'lesson-3': undefined;
  'lesson-4': undefined;
  'lesson-5': undefined;
  'lesson-6': undefined;
  'lesson-7': undefined;
  'lesson-8': undefined;
  'lesson-9': undefined;
  'lesson-10': undefined;
  'lesson-11': undefined;
  'lesson-12': undefined;
  'lesson-13': undefined;
  'lesson-14': undefined;
  'lesson-15': undefined;
  'lesson-16': undefined;
  'lesson-17': undefined;
  'lesson-18': undefined;
  'lesson-19': undefined;
  'lesson-20': undefined;
  'lesson-21': undefined;
  'lesson-22': undefined;
};

export type MenuItem = {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  color: string;
  route: keyof RootStackParamList;
}; 